services:
  - type: web
    name: instagram-private-api-server
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
